// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCRWDISiv_OZqddhfkSXzBJ8eHdYjX0nKE',
    appId: '1:183913286128:android:f9396dea15d87121b1f535',
    messagingSenderId: '183913286128',
    projectId: 'sejalurapp',
    storageBucket: 'sejalurapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDbGwV04NfrlDmj6RohivMiMg8A_vQWjo0',
    appId: '1:183913286128:ios:4ac46f5502be6c0cb1f535',
    messagingSenderId: '183913286128',
    projectId: 'sejalurapp',
    storageBucket: 'sejalurapp.appspot.com',
    iosClientId: '183913286128-j3k972ae5bvrhjrp21pq08hfl00bdf3t.apps.googleusercontent.com',
    iosBundleId: 'com.example.sijalurApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDbGwV04NfrlDmj6RohivMiMg8A_vQWjo0',
    appId: '1:183913286128:ios:4ac46f5502be6c0cb1f535',
    messagingSenderId: '183913286128',
    projectId: 'sejalurapp',
    storageBucket: 'sejalurapp.appspot.com',
    iosClientId: '183913286128-j3k972ae5bvrhjrp21pq08hfl00bdf3t.apps.googleusercontent.com',
    iosBundleId: 'com.example.sijalurApp',
  );
}
